### ISSUE TITLE
Integrate the new Notion Webhooks

### ISSUE THREAD

**Issue by mihirmodak** [mihirmodak/the-notion-cookbook-bot#14]
## Tasks

- [x] Look into how Notion Webhooks can be triggered
- [x] Check if the API can be integrated
- [x] Add the webhook from the Notion UI side
- [x] Add the webhook (callback?) in the app

**Comment by mihirmodak** [comment]
Closed by 47c47da
